### PR TITLE
KDE Fixes

### PR DESCRIPTION
**Pull request by ColonelPanics**
This PR: 
- Prevents screenlock from occurring on KDE desktops
- Installs a polkit file to prevent prompts for passwords to do admin-y things like NetworkManager stuff (leading to users being unable to modify network settings).
- Disables KDE Connect (as this has been observed to show a segfault pop-up box for users when desktops are launched - EL9 specific) 

Tested working as expected on Rocky 9 and CentOS 8.

Patches for screenlock and polkit initially submitted from @mjtko testing on Rocky 8.

### CODE REVIEW

**Comment by VoxSecundus** [comment]
I'm also seeing a segmentation fault error WRT `KDE Discover`. Running this branch on Rocky 9.

Screenshot_2024-05-30_11-58-17

**Comment by ColonelPanics** [comment]
> I'm also seeing a segmentation fault error WRT `KDE Discover`. Running this branch on Rocky 9.

This should be fixed by [cd64dc6](https://github.com/openflighthpc/flight-desktop-types/pull/16/commits/cd64dc6cfe36335d9edda8c580861a75f6e3be00), this will disable the service for Discover Notifier. To test I'd recommend creating a new user on your test system and launching a desktop (as, from my experience, these errors only seem to pop-up on first launch).

That commit also completely removes KDE Connect because we don't need it and, while trying (and failing) to reproduce your error, I got the KDE connect segfault pop-up.

**Comment by VoxSecundus** [comment]
Creating a new user and starting a desktop under that user still gave me the following:

Screenshot_2024-05-30_15-18-39

I killed the processes named `kdeconnectd`, tried again, and didn't get the big popup, but did get smaller ones on the bottom right of the screen.

**Review by VoxSecundus — APPROVED** [review]
Thanks for your work on this and the changes needed after testing; LGTM

**Pull request merged**
